### ISSUE TITLE
PDFviewer not working

### ISSUE THREAD

**Issue by oradke** [owncloud/guests#102]
When clicking on a shared PDF file as a guestr user, I get an error msg:
"Access to this resource is forbidden for guests."

As a standard user, the file loads in the built-in PDF viewer.

**Comment by pmaier1** [comment]
With the Guests app you have the possibility to whitelist apps that guests may access. To do this you need to navigate to the admin panel section 'Sharing' and add 'files_pdfviewer' to the whitelist in the Guests app section. You can do the same for other apps that you want to provide to guests, of course.

In the current release there is a bug that prevents the Guests app section from being displayed in the admin panel which is the reason why you probably didn't find the settings. This will be fixed with the next release of the app.

As a quick workaround you can do the following:

Edit 'app/guest/settings/admin.php' (line ~46) and replace 'guest' with 'sharing' so it looks like

```
....
        public function getSectionID() {
                return 'sharing';
        }
....
```

I hope this answers your question. If it does, please close the ticket. Thanks!

**Comment by oradke** [comment]
Awesome! That did the trick. 
- PDF viewer works
- Guest app settings shows up in the "sharing" tab. (I've been editing the guest settings directly in the database before this fix!)

Question: The whitelisting works, but it's neither intuitive nor documented at all. Would it be possible to create a UI snipped with checkboxes or radio buttons that allows easy whitelisting of components by point and click?

Thanks!
Oliver

**Comment by pmaier1** [comment]
Nice! Glad this was helpful for you. 

> Question: The whitelisting works, but it's neither intuitive nor documented at all. Would it be possible to create a UI snipped with checkboxes or radio buttons that allows easy whitelisting of components by point and click?

In the README of this repository are at least some quick words about app whitelisting. Regarding your UI question this currently is not planned as things essentially work and there are other topics that have higher priority regarding the guests app (e.g. ability to resend invites or ability to see if your invites were accepted and some more; have a look at the tickets in this repo if you're interested).

As your feature request is definitely important for the future I would ask you to file a separate ticket where we can come back to at a later point! Thanks a lot!
