### ISSUE TITLE
Guest user should be prevented from login if he has no more shares

### ISSUE THREAD

**Issue by IljaN** [owncloud/guests#12]

**Comment by PVince81** [comment]
A possibly easy way to detect this: after setupFS and mount point init if the "files" folder is empty, it means there are no more shares.

**Comment by felixheidecke** [comment]
This would collide with guests, that only use apps such as calendar, contacts etc.

**Comment by hodyroff** [comment]
Hmm, I think it would be fine to define that guests need to have shared a file for login at this time. A pure solution which does not concentrate on file sharing sounds undesired right now and the workaround is easy. You enable a guest with a file share and you disable a guest that way. You can't enable a guest with a contact or calendar share, so those should be second thoughts for now.
@pmaier1

**Comment by pmaier1** [comment]
1) We don’t have proper app whitelisting for guests currently, so guest accounts are only for file exchange officially.
2) If a guest does not have shares he can hardly use apps (Why would I use a calendar or contacts or other 'standalone' app in a guest account of someone else's ownCloud instance? I think this is rather useful for stuff like Collabora which again only makes sense if you have files shared with you)

We need to think about it again when we have a concept/implementation for giving selective access to apps for guests. For now a guest account should become disabled when there are no shares left.

**Comment by PVince81** [comment]
> concept/implementation for giving selective access to apps for guests

The implementation is already there but might be useless in its current state for the reasons you stated above (why use calendar/contact). Guest users will be members of a special group "guests" so it is possible to use the "Enable app only for these groups" feature and select the "guests" group. This will have no visible effect.

Just stating this for the sake of completeness 😄

**Comment by pmaier1** [comment]
> "Enable app only for these groups" feature and select the "guests" group. This will have no visible effect. 

Yes, I'm aware of that but
1. Many apps don't allow to be limited to groups
2. With the current implementation you can either enable an app for all guests or for none, nothing in between
3. When I want to make an app available for guests, I also need to specify all other groups that need access

**Comment by IljaN** [comment]
After some reconsiderations with @PVince81 and @pmaier1 this will not be implemented.

**Comment by PVince81** [comment]
Writing down some of the complications here for future reference, in case they are useful:

- detecting how many shares the user is receiving at login time is possible but would need consolidating with the later setupFS code that also does the same. So would need to implement local caching (scoped to PHP request) of the received shares list to avoid the second call refetching the same info. Technically possible but rather complicated
- the other approach is to have the guest app's code check the number of shares at creation/deletion time of shares, and then enable/disable the user using the users API (enable/disable is an existing feature). However an admin might have already manually disabled a user and does not wish for regular users to have the ability to reenable such users by creating shares.

In the end, the complexity of the implementation outweighs the benefits of this minor requirement.

It does not hurt if a user can still log in but not do anything.

However it was pointed out that it should be possible for an admin to get a list (config report?) of guest users who have no shares so that the admin can decide to delete these manually after a while.
