### ISSUE TITLE
Cannot disable comments application for guests users

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#136]
![screen shot 2017-08-21 at 09 17 38](https://user-images.githubusercontent.com/10596560/29508985-de1645aa-8656-11e7-9e6b-735f9aea7335.png)

Comment application is always enabled for guests users. It also happens with other apps like files_viadoplayer etc

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - customgroups: 0.3.4
  - dav: 0.3.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - guests: 0.4.1
  - market: 0.2.1
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_shibboleth: 3.1
```

**Comment by pmaier1** [comment]
Hm, interesting. Are the apps usable? Meaning that a guest can actually create comments or watch videos?

**Comment by davitol** [comment]
Yes, guest user can create comments

**Comment by pmaier1** [comment]
> Yes, guest user can create comments

Ok, then we should check for other apps that can't be disabled as well and find the reason in a next iteration. Thanks!

**Comment by PVince81** [comment]
From what I see after a quick look in the code, it is likely that this whitelist only works for full page apps like calendar, contacts, not for apps that integrate themselves into the files app.

Disabling apps that integrate themselves into the files app is likely more tricky. Another way would be to use the "enable only for users" in the apps page for these apps instead.

We also can't provide a hook "onLoadApp" from core because even if the guest app could listen to it, it is not guaranteed that the guests app is loaded before the other apps it is wanting to check against... Needs further research.

**Comment by PVince81** [comment]
@pmaier1 move to "planned" as it's no release blocker ?

**Comment by pmaier1** [comment]
> @pmaier1 move to "planned" as it's no release blocker ?

'development' is the right place. Depending on efforts I would maybe also postpone this as it's not that critical and there are other ways to achieve the behavior as suggested above. Needs some research. If we can include it in the next development iteration, nice, if not we move it to 'planned'/'triage'.

**Comment by pmaier1** [comment]
This can be closed due to https://github.com/owncloud/guests/pull/165, right?

**Comment by cortho** [comment]
follow ups there: #163
