### ISSUE TITLE
Guest users can have the same name

### ISSUE THREAD

**Issue by davitol** [owncloud/guests#142]
![screen shot 2017-08-22 at 11 05 42](https://user-images.githubusercontent.com/10596560/29561777-10fe53aa-8737-11e7-9f29-69d788a4f2c0.png)

@pmaier1 Guest users with different email can have the same name in oC. Should we add a restriction in other to avoid it?

**Comment by pmaier1** [comment]
This is a general problem. Every user can change the display name ('full name') to an existing one. You can't even say in the sharing dialog which one is the one you need. In my example (see screenshot) I created two users, "test2" and "test3" and changed their display names to "hallo".

![screenshot from 2017-08-30 17-47-51](https://user-images.githubusercontent.com/21193500/29881934-e8530344-8dab-11e7-9af2-35fcb704701f.png)

We therefore need a general solution for this. Options:
- Restrict display names to be unique (not that nice IMO)
- Add some other differentiator to the display name, e.g. mail address in parentheses -> Ana (x@y.tld); maybe only in the duplicate case?
- Instead of display name show the user name in the duplicate case?
- other ideas?

This is nothing guests-specific and needs a core ticket. Probably there already is one.

@PVince81 when time permits.

**Comment by PVince81** [comment]
Raised here: https://github.com/owncloud/core/issues/28979

**Comment by cdamken** [comment]
> This is a general problem. Every user can change the display name ('full name') to an existing one. You can't even say in the sharing dialog which one is the one you need. In my example (see screenshot) I created two users, "test2" and "test3" and changed their display names to "hallo".

The administrator is able to block users to modify the `Displayname`
https://github.com/owncloud/core/blob/v10.0.3/config/config.sample.php#L179-L183

But there is still this bug: https://github.com/owncloud/core/issues/27442

**Comment by PVince81** [comment]
with the latest master you cannot specify a name any more, you create guests directly by email address. So this bug is obsolete on the guests side

**Comment by PVince81** [comment]
Hmm right, the display name. Reopening.

**Comment by PVince81** [comment]
Hmm right, the display name. Reopening.

**Comment by pmaier1** [comment]
> Hmm right, the display name. Reopening.

This is solved with the "solution for indistinguishable display names" we introduced with 10.0.4, right?

**Comment by PVince81** [comment]
Guests are able to set display names, so two guests could set the same name.

But if the admin set the new core option to always display the email address in the sharing autocomplete, then it will be possible to distinguish these users, yes.

**Comment by davitol** [comment]
With tooltips

![screen shot 2017-12-13 at 14 07 06](https://user-images.githubusercontent.com/10596560/33940361-f1edf0a2-e00e-11e7-8211-577e7ac5524a.png)


With the new option to display the email address

![screen shot 2017-12-13 at 14 06 17](https://user-images.githubusercontent.com/10596560/33940385-08e8857e-e00f-11e7-9deb-20e9ac36c9ff.png)


So IMHO it is fine to close the ticket. @pmaier1 @PVince81

**Comment by pmaier1** [comment]
Assuming that the API response also contains the mail address if enabled I close this now. Please reopen if this is not the case. A general guest identifier like an icon or "(guest)" would still be very helpful but that's actually another topic.
