### ISSUE TITLE
Create guest when email is not known

### ISSUE THREAD

**Issue by PVince81** [owncloud/guests#145]
Some people do not have an email address or do not know it (elderly people in some case) or do not want to share their email addresses, but are still available per chat (Facebook, whatever).

It would be nice to be able to create a guest link and be able to copy this one from the dialog after creation, to be able to send this link by chat / sms / snail mail / whatever is available.

It would work this way:

1. Type in the name of the guest in the share dropdown and select it
1. In the guest creation dialog, don't enter any email address
1. Click Save
1. Success dialog appears with the guest link in question + a clipboard copy icon

Optionally, it should be possible to call up this dialog + link again to be able to copy the link again or even revoke it. (a bit like link shares)

Another addition would be to always display this link even if an email was sent, and allow calling up the dialog again for existing guests who haven't created an account yet.

@pmaier1 @cortho @butonic thoughts ?

**Comment by PVince81** [comment]
This is mostly useful for non-admins.

Admin users could simply manually create a new account add add it to the "guest_app" group.

**Comment by PVince81** [comment]
Okay, there is another ticket for the ability to find out what guest shares were created: https://github.com/owncloud/guests/issues/87

**Comment by butonic** [comment]
hm
- username should then use an RFC UUID: https://tools.ietf.org/html/rfc4122
- how can oc authenticate the guest?
  - by token? this would be semantically equivalent to multiple share links
  - by linking the guest to his twitter / fb account? but for those you need an email as well don't you?
  - by sending an sms if the sharer supplied a phone number? 
  - hm ... by login / password. but this only works if we ask the guest to set a login / password for his account. this would require using the userid column in the account table as the login and the accountid everywhere else.

cc @tomneedham thoughts on user management

**Comment by cortho** [comment]
@PVince81 because of the virtual group characteristics it is currently _not possible_ creating guest users by just adding them to the guests group, see https://github.com/owncloud/guests/issues/91 for example.

I do not understand the need for this (maybe you want to elaborate), aren't Public Link Shares well suited for such users? Or why not create a real user without email address? What is the use case here?

There sure would be some more open questions, such as how those guests could reset the password.

for #87 you mentioned above I made this PR https://github.com/owncloud/guests/pull/126, but recently I didn't have the time to write the tests due to other priorites atm.

**Comment by PVince81** [comment]
Public link shares cannot be used with the desktop client.

My use case is mostly for people who do not know how to use email (ex: some older family members of mine), I'd create a guest account for them on my instance and send them the password by... hmmm...

Yeah maybe the whole thing isn't secure. And as @butonic pointed out you cannot guarantee that the recipient is whoever you sent the link to.

Feel free to close.

**Comment by cortho** [comment]
would not be possible with #147 anyway -> closing
