### ISSUE TITLE
improve feature descriptions

### ISSUE THREAD

**Issue by felixboehm** [owncloud/guests#162]
1. Improve existing feature scenarios
- Scenario: Creating a guest user works fine
- Scenario: A guest user cannot upload files
- Scenario: A guest user can upload files
- Scenario: A guest user can upload a file and can reshare it
- Scenario: A guest user cannot reshare files
- Scenario: Check that skeleton is properly set
- Scenario: A created guest user can log in
- Scenario: Trying to create a guest user that already exists
- Scenario: removing a user from a group

Just reading the scenarios above: wtf?
Please describe the guest functionality so that the scenarios specify (understandable) the functionality.

Then please add scenarios for missing functionalities of the guest app and its settings:
- Scenario: A guest user has only access to whitelisted apps
...

See: https://github.com/owncloud/guests/blob/master/tests/integration/guests_features/Guests.feature

**Comment by davitol** [comment]
> Improve existing feature scenarios
> 
>     Scenario: Creating a guest user works fine
>     Scenario: A guest user cannot upload files
>     Scenario: A guest user can upload files
>     Scenario: A guest user can upload a file and can reshare it
>     Scenario: A guest user cannot reshare files
>     Scenario: Check that skeleton is properly set
>     Scenario: A created guest user can log in
>     Scenario: Trying to create a guest user that already exists
>     Scenario: removing a user from a group
> 
> Just reading the scenarios above: wtf?

* Admin user creates a guest user via email and the response is 201
* Admin user creates a guest user via email and the guest user cannot upload files in the folder shared due to can edit permission was not set
* Admin user creates a guest user via email and the guest user cannot upload files in the folder shared due to can edit permission was set
* Admin user creates a guest user via email and the guest user cannot upload files in the folder shared due to can edit and can reshare permissions were set
* Admin user creates a guest user via email and the guest user cannot upload files in the folder shared due to reshare permission was not set
* A guest user can log in after being created via mail sharing a file with him by an admin user
* Admin user tries to create a guest user via email setting an already used email for other guest user and the response is 422
* Admin user removes a guest user from the default guest_app groups

@felixboehm @pmaier1 @cortho Something like this?

**Comment by pmaier1** [comment]
Looks way better than the existing descriptions, I think! Still I think we need to take care about the outcomes of certain scenarios, e.g. what happens in this scenario?:

> Admin user removes a guest user from the default guest_app groups

Also putting things like "can edit" permission in "" makes it easier readable.

**Comment by SergioBertolinSG** [comment]
Honestly I think this is not an improvement, the title of the scenario should describe what is the goal of the test. All those details are already included in the steps of each scenario.

**Comment by cortho** [comment]
I was fine with the current titles and for me it was clear what the scenarios were doing, since, as a developer, I had to look into the bootstrap directiory as well.
Hovever, before I can make my opinion on this: who is going to read the scenario titles anyway and what should be accomplished when they are _more readable_?

**Comment by davitol** [comment]
I'm agree with @SergioBertolinSG and @cortho's comments. I also prefer the current titles, not sure how to improve them.

**Comment by phil-davis** [comment]
I think the "problem" is that all the scenarios are in a single feature file. The Behavior-Driven-Development (BDD) approach is to use a feature file for every separate end-user "feature" or "business-user-requirement". At the top of the feature file (before the "Background" or "Scenario" sections) the feature is described. Those lines are actually free-text in Behat, but it is conventional to write the feature description in the format:
```
As a [role]
I want [feature]
So that [benefit]
```
The classic early descriptions of BDD were by Dan North, e.g. https://dannorth.net/whats-in-a-story/

So if we make more Behat "feature" files with good names and feature descriptions, it is easier to understand.

In practice I think it is often also useful to put some explanation about the feature (might be constraints on how the feature is implemented, how it should fit in the business workflow...)

Then the scenarios are specific use-case examples of how the workflow of the feature should work. Product managers with end-users should be able to write normal "success" scenarios that illustrate the expected workflow, and that illustrate the "normal" error cases (when users enter invalid data...). Often in practice it is then up to QA with developers to think through other edge cases that would be useful to test, and add scenarios for those.

It would be nice for product managers/users to write a "feature" file for a proposed new feature, along with scenarios that are tagged "@skip" at first. Then developers work on adding the feature, writing unit tests, writing the acceptance tests underneath the scenarios and "unskipping" scenarios as they make those tests pass. When all scenarios pass, then by definition the feature is ready for delivery.

**Comment by individual-it** [comment]
Some thoughts to discuss that might improve our feature descriptions (partly mentioned above):

**1. use declarative description of the tests.**
- Use a language that all stakeholders do understand (PM, dev, QA)
- Hide away the implementation details in the PHP code

tests like this one https://github.com/owncloud/core/blob/master/tests/ui/features/sharing/sharing.feature#L32-L48
could be rephrased in a way the "I login as ..." and "I logout" are hidden away

**2. Split every feature into a separate file**
if a feature gets to complicated e.g to many variations split it further

**3. Combine features into Suites**
features that kind of belong together can go into one suite

**4. write a good description for every feature**
Answer the question: Who wants to achieve what?

**5. keep Scenarios short**
there is a trade-off here because every setup costs time. So specially in UI tests one long scenario with only one user setup and login would run much faster than multiple short scenarios

**6. make other stakeholders to review your feature files.**
If BDD is all about improving communication between different parties in the dev. process, all parties should agree on the description of the feature and the step definition. If QA wrote a feature and PM has no idea what the description is about or what the steps do, its probably not declarative enough

**7. be consistent in the step definition**
do we use 'When I'm login as "admin"' or 'Given As "admin"'?
do we use 'When I copy a file' or 'When a file is copied'?

**8. let a native speaker check your language & grammar**
I'm really bad at that, in any given language, @phil-davis is my spelling saviour :-)

**Comment by phil-davis** [comment]
**9. get stakeholders to write feature files**
for new proposed features or even for features that are not tested yet
(this is the ideal place to get to with BDD - the stakeholder writes the feature file, then "the team" reviews and negotiates some of the wording, and then the implementation of tests and code is assigned in "the team")

**Comment by individual-it** [comment]
made someone reading our UI tests feature files and figured out its hard to understand some of the tests when you don't know the content of the skeleton folder

**Comment by individual-it** [comment]
can/should we allow multiple 
```
As a [role]
I want [feature]
So that [benefit]
```
blocks in one feature?

E.g.:
```
As a user
I want to be able to rename files and folders
So that I can organize my data

As an administrator
I want to make sure only legal characters are used in file names
So that the filesystem and database does not get corrupted and the system is not exposed to security risks
```

**Comment by individual-it** [comment]
please have a look at https://github.com/owncloud/core/pull/29370
there is an proposal how the explanation lines could look like

**Comment by SergioBertolinSG** [comment]
Ok all this suggestions by @individual-it and @phil-davis sound good.

Regarding the part about involving stakeholders more to write feature files or review them, I disagree. That would slow test development. 

I agree with having a description about what is expected of an app or feature, that's great. And including more people in the reviews just in case they want to review. But not making it a mandatory process.

**Comment by phil-davis** [comment]
For existing behavior, when we are actually reverse-engineering the "requirements/features" and making relevant scenarios to test, then I agree that is "QA technical debt" work for the QA/testing team.

For new behavior, it would be nice if those proposing the behavior can work with QA-testing-development to write a feature file(s) describing the feature(s) and with example scenarios. Then QA-testing can help refine the feature-scenario files. Then it is a team effort (development-QA-test) to make the actual test code underneath the scenarios, and the application code that is the actual feature. When the feature-scenarios pass then the new behavior is ready to deliver (to whatever manual testing-QA remains)

Yes, it is not reasonable to expect that end users or "product managers" or similar will write their own feature-scenario files by themselves.

**Comment by individual-it** [comment]
for **[7. be consistent in the step definition](https://github.com/owncloud/guests/issues/162#issuecomment-338898309)** in UI tests
I would suggest to use first person `When I copy a file` when its about an action that is done through the UI and third person `When a file is copied` in cases when the action is done by any other means, e.g. by `occ` or a HTTP API.
Currently we mix both, to make it uniform a little bit of refactoring would be needed but it should not be too much.

**Comment by individual-it** [comment]
moved discussion to QA repo https://github.com/owncloud/QA/issues/517
